import type { NextFunction, Request, Response } from "express";
import { httpError } from "../utils/httpError";
import { generateText, MODELS } from "../lib/ai/openrouter";
import {
  analyzeDocument,
  detectAIContent,
  detectSimilarity,
  checkCitations,
  analyzeWritingQuality,
  type PlagiarismConfig,
} from "../services/plagiarism-checker.service";

const reportStore = new Map<string, any>();

// POST /api/plagiarism/analyze — SSE streaming full analysis
export async function analyzePlagiarismSSE(req: Request, res: Response) {
  const config = req.body as PlagiarismConfig;
  if (!config.text?.trim()) {
    res.status(400).write(`data: ${JSON.stringify({ type: "error", message: "Text is required for analysis" })}\n\n`);
    res.end();
    return;
  }

  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");
  res.flushHeaders();

  const sendEvent = (data: Record<string, unknown>) => {
    res.write(`data: ${JSON.stringify(data)}\n\n`);
    if (typeof (res as any).flush === "function") (res as any).flush();
  };

  try {
    sendEvent({ type: "progress", step: "init", message: "Starting document analysis...", percent: 3 });

    const report = await analyzeDocument(
      {
        text: config.text,
        title: config.title,
        checkAI: config.checkAI !== false,
        checkSimilarity: config.checkSimilarity !== false,
        checkCitations: config.checkCitations !== false,
        checkWritingQuality: config.checkWritingQuality !== false,
      },
      (step, message, percent) => {
        sendEvent({ type: "progress", step, message, percent });
      }
    );

    const reportId = `report-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    reportStore.set(reportId, report);
    if (reportStore.size > 50) {
      const keys = Array.from(reportStore.keys());
      for (let i = 0; i < keys.length - 50; i++) reportStore.delete(keys[i]);
    }

    sendEvent({ type: "complete", reportId, report });
  } catch (err: any) {
    sendEvent({ type: "error", message: err.message || "Analysis failed" });
  } finally {
    res.end();
  }
}

// POST /api/plagiarism/analyze-sync — Non-streaming fallback
export async function analyzePlagiarismSync(req: Request, res: Response, next: NextFunction) {
  const config = req.body as PlagiarismConfig;
  if (!config.text?.trim()) { next(httpError(400, "Text is required")); return; }
  try {
    const report = await analyzeDocument({
      text: config.text,
      title: config.title,
      checkAI: config.checkAI !== false,
      checkSimilarity: config.checkSimilarity !== false,
      checkCitations: config.checkCitations !== false,
      checkWritingQuality: config.checkWritingQuality !== false,
    });
    res.json({ success: true, report });
  } catch (err: any) {
    next(httpError(500, err.message || "Analysis failed"));
  }
}

// GET /api/plagiarism/report/:id
export async function getReport(req: Request, res: Response, next: NextFunction) {
  const id = String(req.params.id);
  const report = reportStore.get(id);
  if (!report) { next(httpError(404, "Report not found")); return; }
  res.json({ success: true, report });
}

// POST /api/plagiarism/humanize — Rewrite AI-generated text to sound human
export async function humanizeText(req: Request, res: Response, next: NextFunction) {
  const { text } = req.body as { text?: string };
  if (!text?.trim()) { next(httpError(400, "Text is required")); return; }
  try {
    const content = await generateText(
      `You are an expert academic writer. Your task is to "humanize" text that may have been generated by AI. Make it sound naturally written by a knowledgeable human researcher.

Key techniques:
- Add subtle imperfections and personal voice
- Vary sentence length and structure significantly
- Use domain-specific jargon naturally
- Add transitional phrases that feel organic
- Include occasional complex/compound sentences
- Maintain all factual accuracy and technical content`,
      `Rewrite this text to sound naturally human-written while preserving all technical meaning:\n"""\n${text}\n"""\nReturn ONLY the rewritten text. Maintain academic tone. Do not add explanations.`,
      { model: MODELS.FAST }
    );
    res.json({ success: true, content });
  } catch (err: any) {
    next(httpError(500, err.message || "Humanization failed"));
  }
}

// POST /api/plagiarism/rewrite-section — Rewrite a specific flagged section
export async function rewriteSection(req: Request, res: Response, next: NextFunction) {
  const { text, reason } = req.body as { text?: string; reason?: string };
  if (!text?.trim()) { next(httpError(400, "Text is required")); return; }
  try {
    const instruction = reason === "ai"
      ? "Rewrite to sound more human-written and natural. Add personal academic voice."
      : reason === "similarity"
      ? "Rewrite to be completely original while preserving the meaning. Use different vocabulary and sentence structures."
      : "Improve this text for academic quality while preserving meaning.";

    const content = await generateText(
      `You are an expert academic paraphraser. ${instruction} Maintain all technical accuracy and facts.`,
      `Rewrite:\n"""\n${text}\n"""\nReturn ONLY the rewritten text.`,
      { model: MODELS.FAST }
    );
    res.json({ success: true, content });
  } catch (err: any) {
    next(httpError(500, err.message || "Rewrite failed"));
  }
}
